---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: myapp-db
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
      - name: postgresql
        image: postgres:13-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: news
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: myapp-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
